name: NASM CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  before-script:
    runs-on: ubuntu-latest
    steps:
      - name: before-script
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get -y install gcc g++ make nasm binutils

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: chmod +x test/all && test/all
