name: NASM CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: before-script
        run: sudo apt-get -y install gcc g++ make nasm binutils
      - name: test
        run: chmod +x test/all.sh && test/all.sh
